version: '3.8'

services:
  # Primary Database (writes + reads)
  postgres-primary:
    image: postgres:16-alpine
    container_name: dbx-demo-primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - primary_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Read Replica 1
  postgres-replica1:
    image: postgres:16-alpine
    container_name: dbx-demo-replica1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5433:5432"
    volumes:
      - replica1_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      postgres-primary:
        condition: service_healthy

  # Read Replica 2
  postgres-replica2:
    image: postgres:16-alpine
    container_name: dbx-demo-replica2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5434:5432"
    volumes:
      - replica2_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      postgres-primary:
        condition: service_healthy

volumes:
  primary_data:
  replica1_data:
  replica2_data:
